import * as z from "zod";
import { buildProjectTree } from "@/lib/projectTree";
import type { FileExplanation, Technology } from "@/types/analysis";
import type { LiveRepositoryAnalysis } from "@/types/live-analysis";

// Validate the parts of the API response used by the report.
// Retain file-reading metadata, but strip raw code and repositoryContext.
const responseSchema = z.object({
  repository: z.object({
    name: z.string().min(1),
    fullName: z.string().regex(/^[^/]+\/[^/]+$/),
    description: z.string().nullable(),
    language: z.string().nullable(),
    defaultBranch: z.string().min(1),
    url: z.url(),
    stars: z.number().int().nonnegative().optional(),
    license: z.string().nullable().optional(),
  }),
  technologies: z.array(z.string()),
  tree: z.array(z.object({ path: z.string(), type: z.string() })),
  importantFiles: z.array(z.object({ path: z.string(), type: z.string() })),
  fileContents: z
    .array(z.object({
      path: z.string(),
      truncated: z.boolean().default(false),
      error: z.string().nullable().default(null),
    }))
    .default([]),
  overview: z.object({
    summary: z.string().min(1),
    targetAudience: z.string().min(1),
    limitations: z.array(z.string()),
    fileExplanations: z
      .array(z.object({
        path: z.string(),
        purpose: z.string(),
        significance: z.string(),
      }))
      .default([]),
  }),
});

export function mapRepositoryResponse(value: unknown): LiveRepositoryAnalysis {
  const parsed = responseSchema.safeParse(value);

  if (!parsed.success) {
    throw new Error(
      "The server returned an incomplete analysis. Please try again.",
    );
  }

  const data = parsed.data;
  const fileDetails = new Map(data.fileContents.map((file) => [file.path, file]));
  const importantPaths = new Set(data.importantFiles.map((file) => file.path));
  const explanations = new Map<string, FileExplanation>();

  for (const explanation of data.overview.fileExplanations) {
    const purpose = explanation.purpose.trim();
    const significance = explanation.significance.trim();
    if (
      importantPaths.has(explanation.path) &&
      !fileDetails.get(explanation.path)?.error &&
      !explanations.has(explanation.path) &&
      purpose &&
      significance
    ) {
      explanations.set(explanation.path, {
        path: explanation.path,
        purpose,
        significance,
      });
    }
  }

  const frameworks = new Set([
    "Next.js",
    "React",
    "Vue",
    "Angular",
    "Svelte",
    "Express",
    "Django",
    "Flask",
    "FastAPI",
  ]);

  const technologies: Technology[] = [...new Set(data.technologies)].map(
    (name) => ({
      name,
      category: "Detected technology",
      description:
        "Detected from repository metadata, dependencies, or file paths.",
      mark: name.slice(0, 2).toUpperCase(),
      color: "ink",
    }),
  );

  return {
    repository: {
      name: data.repository.name,
      owner: data.repository.fullName.split("/")[0],
      description:
        data.repository.description ?? "No repository description provided.",
      language: data.repository.language ?? "Not reported",
      framework:
        data.technologies.find((name) => frameworks.has(name)) ??
        "Not identified",
      stars: data.repository.stars?.toLocaleString("en-US") ?? "Unknown",
      branch: data.repository.defaultBranch,
      url: data.repository.url,
      license:
        data.repository.license === undefined
          ? "Unknown"
          : (data.repository.license ?? "Not specified"),
    },
    overview: {
      ...data.overview,
      fileExplanations: [...explanations.values()],
    },
    technologies,
    structure: buildProjectTree(data.repository.name, data.tree),
    importantFiles: data.importantFiles.map((file) => {
      const explanation = explanations.get(file.path);
      const details = fileDetails.get(file.path);

      return {
        path: file.path,
        type: file.type,
        purpose: explanation?.purpose ?? "No file explanation available.",
        significance: explanation?.significance ?? (
          details?.error
            ? "The file could not be read for this analysis."
            : "The analysis did not return an explanation for this file."
        ),
        explanationStatus: explanation ? "available" : "unavailable",
        truncated: details?.truncated ?? false,
      };
    }),
    // These analyses are not generated by the current backend yet.
    architecture: [],
    steps: [],
    improvements: [],
  };
}
