import * as z from "zod";
import type { ProjectNode, Technology } from "@/types/analysis";
import type { LiveRepositoryAnalysis } from "@/types/live-analysis";

// Validate the parts of the API response used by the report.
// Zod strips unrelated fields such as fileContents and repositoryContext.
const responseSchema = z.object({
  repository: z.object({
    name: z.string().min(1),
    fullName: z.string().regex(/^[^/]+\/[^/]+$/),
    description: z.string().nullable(),
    language: z.string().nullable(),
    defaultBranch: z.string().min(1),
    stars: z.number().int().nonnegative().optional(),
    license: z.string().nullable().optional(),
  }),
  technologies: z.array(z.string()),
  tree: z.array(z.object({ path: z.string(), type: z.string() })),
  importantFiles: z.array(z.object({ path: z.string(), type: z.string() })),
  overview: z.object({
    summary: z.string().min(1),
    targetAudience: z.string().min(1),
    limitations: z.array(z.string()),
  }),
});

function buildProjectTree(
  name: string,
  entries: { path: string; type: string }[],
): ProjectNode {
  const root: ProjectNode = { name, children: [] };
  const nodes = new Map<string, ProjectNode>([["", root]]);

  for (const entry of entries) {
    // Git trees contain blobs (files), trees (folders), and commits (submodules).
    if (!["blob", "tree", "commit"].includes(entry.type)) continue;

    const parts = entry.path.split("/").filter(Boolean);
    let parent = root;
    let currentPath = "";

    parts.forEach((part, index) => {
      currentPath = currentPath ? `${currentPath}/${part}` : part;
      const isFolder = index < parts.length - 1 || entry.type === "tree";
      let node = nodes.get(currentPath);

      if (!node) {
        node = isFolder ? { name: part, children: [] } : { name: part };
        nodes.set(currentPath, node);
        (parent.children ??= []).push(node);
      }

      if (isFolder) node.children ??= [];
      if (entry.type === "commit" && index === parts.length - 1) {
        node.description = "Git submodule";
      }
      parent = node;
    });
  }

  function sortChildren(node: ProjectNode) {
    node.children?.sort((a, b) => {
      const foldersFirst =
        Number(Boolean(b.children)) - Number(Boolean(a.children));
      return foldersFirst || a.name.localeCompare(b.name);
    });
    node.children?.forEach(sortChildren);
  }

  sortChildren(root);
  return root;
}

export function mapRepositoryResponse(value: unknown): LiveRepositoryAnalysis {
  const parsed = responseSchema.safeParse(value);

  if (!parsed.success) {
    throw new Error(
      "The server returned an incomplete analysis. Please try again.",
    );
  }

  const data = parsed.data;
  const frameworks = new Set([
    "Next.js",
    "React",
    "Vue",
    "Angular",
    "Svelte",
    "Express",
    "Django",
    "Flask",
    "FastAPI",
  ]);

  const technologies: Technology[] = [...new Set(data.technologies)].map(
    (name) => ({
      name,
      category: "Detected technology",
      description:
        "Detected from repository metadata, dependencies, or file paths.",
      mark: name.slice(0, 2).toUpperCase(),
      color: "ink",
    }),
  );

  return {
    repository: {
      name: data.repository.name,
      owner: data.repository.fullName.split("/")[0],
      description:
        data.repository.description ?? "No repository description provided.",
      language: data.repository.language ?? "Not reported",
      framework:
        data.technologies.find((name) => frameworks.has(name)) ??
        "Not identified",
      stars: data.repository.stars?.toLocaleString("en-US") ?? "Unknown",
      branch: data.repository.defaultBranch,
      license:
        data.repository.license === undefined
          ? "Unknown"
          : (data.repository.license ?? "Not specified"),
    },
    overview: data.overview,
    technologies,
    structure: buildProjectTree(data.repository.name, data.tree),
    importantFiles: data.importantFiles.map((file) => ({
      path: file.path,
      type: file.type,
      purpose:
        "Selected as potentially useful for understanding this repository.",
      significance:
        "An explanation of this individual file has not been generated yet.",
    })),
    // These analyses are not generated by the current backend yet.
    architecture: [],
    steps: [],
    improvements: [],
  };
}
